version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - transcription_data:/app/temp
      - transcription_db:/app/data
    environment:
      - FLASK_APP=app.app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - app-network
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  transcription_data:
  transcription_db:

networks:
  app-network:
    driver: bridge 